@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package choonster.forgesubstitutionaliastestmod;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
